---

- name: deploy api
  hosts: all
  remote_user: mateo
  become: yes
  vars:
    symfony_console_path: /var/www/html/ecommerce2/symfony5/bin/console

  tasks:
    - name: checkVersion
      fail:
        msg: "Use  Debian10"
      when: ansible_distribution != "Debian" or ansible_distribution_version < "10"
    - name: tranferFiles
      synchronize:
        src: /var/www/html/symfony5
        dest: /var/www/html/ecommerce2
    - name: createDB
      command: '{{ symfony_console_path }} doctrine:database:create --if-not-exists'
    - name: makeMigration
      command: '{{ symfony_console_path }} make:migration --no-interaction'
   
    - name: importTables
      command: '{{ symfony_console_path }} doctrine:migrations:migrate --no-interaction'
   
  handlers:
    - name: RestartNginx
      service:
        name: nginx
        state: restarted

    - name: RestartPHP
      service:
        name: php7.3-fpm
        state: restarted 
